image: dhanwada/lsap-pipeline:1.0.0

Shared:
  script:
    - sh ./scripts/ci/install_shared.sh

DiffMapper:
  script:
    - sh ./scripts/ci/install_shared_bypass.sh
    - sh ./scripts/ci/install_diffMapper.sh

DiffLinker:
  script:
    - sh ./scripts/ci/install_shared_bypass.sh
    - sh ./scripts/ci/install_diffLinker.sh
RssReader:
  script:
    - sh ./scripts/ci/install_shared_bypass.sh
    - sh ./scripts/ci/install_rssReaderConcept.sh
Patcher:
  script:
    - sh ./scripts/ci/install_shared_bypass.sh
    - sh ./scripts/ci/install_patchGeneration.sh

DataTranslator:
  script:
    - sh ./scripts/ci/install_shared_bypass.sh
    - sh ./scripts/ci/install_dataTranslator.sh
