image: maven:alpine

job1:
  script:
    - (cd JavaWorkspace/diffMapper; mvn install -B)
    - (cd JavaWorkspace/diffLinker; mvn install -B)
    - (cd JavaWorkspace/rssReaderConcept; mvn install -B)

