image: maven:alpine

DiffMapper:
  script:
    - (cd JavaWorkspace/diffMapper; mvn install -B && cat target/site/jacoco/index.html)

DiffLinker:
  script:
    - (cd JavaWorkspace/diffLinker; mvn install -B && cat target/site/jacoco/index.html)
    
RssReader:
  script:
    - (cd JavaWorkspace/rssReaderConcept; mvn install -B && cat target/site/jacoco/index.html)

Patcher:
  script:
    - (cd JavaWorkspace/patchGeneration; mvn install -B && cat target/site/jacoco/index.html)