image: dhanwada/lsap-pipeline:1.0.0

Shared:
  script:
    - (cd JavaWorkspace/shared; mvn install -B && cat target/site/jacoco/index.html)

DiffMapper:
  script:
    - (cd JavaWorkspace/shared; mvn install -B -Dmaven.test.skip=true)
    - (cd JavaWorkspace/diffMapper; mvn install -B && cat target/site/jacoco/index.html)

DiffLinker:
  script:
    - (cd JavaWorkspace/shared; mvn install -B -Dmaven.test.skip=true)
    - (cd JavaWorkspace/diffLinker; mvn install -B && cat target/site/jacoco/index.html)
    
RssReader:
  script:
    - (cd JavaWorkspace/rssReaderConcept; mvn install -B && cat target/site/jacoco/index.html)

Patcher:
  script:
    - (cd JavaWorkspace/patchGeneration; mvn install -B && cat target/site/jacoco/index.html)
