image: maven:3.5.2-jdk-8-alpine

DiffMapper:
  script:
    - (cd JavaWorkspace/diffMapper; mvn install -B && cat target/site/jacoco/index.html)

DiffLinker:
  script:
    - (cd JavaWorkspace/diffLinker; mvn install -B && cat target/site/jacoco/index.html)

